#! /usr/bin/env python3
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 8.1
#  in conjunction with Tcl version 8.6
#    Oct 17, 2025 04:23:42 PM %z  platform: Windows NT

import tkinter as tk
import tkinter.ttk as ttk
import os.path
from view import interface_support as interface_support

_location = os.path.dirname(__file__)

_bgcolor = '#d9d9d9'
_fgcolor = 'black'
_tabfg1 = 'black' 
_tabfg2 = 'white' 
_bgmode = 'light' 
_tabbg1 = '#d9d9d9' 
_tabbg2 = 'gray40' 

_style_code_ran = 0
def _style_code():
    global _style_code_ran
    if _style_code_ran: return        
    try: interface_support.root.tk.call('source',
                                        os.path.join(_location, 'themes', 'alt.tcl'))
    except: pass
    style = ttk.Style()
    style.theme_use('alt')
    style.configure('.', font = "TkDefaultFont")
    _style_code_ran = 1

class Jogo:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''

        top.geometry("1414x959+115+15")
        top.minsize(120, 1)
        top.maxsize(1924, 1061)
        top.resizable(1,  1)
        top.title("Jogo")
        top.configure(background="#d9d9d9")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")

        self.top = top

        self.fChat = tk.Frame(self.top)
        self.fChat.place(relx=0.552, rely=0.428, relheight=0.512, relwidth=0.434)

        self.fChat.configure(relief='groove')
        self.fChat.configure(borderwidth="2")
        self.fChat.configure(relief="groove")
        self.fChat.configure(background="#d9d9d9")
        self.fChat.configure(highlightbackground="#d9d9d9")
        self.fChat.configure(highlightcolor="black")

        self.lChat = tk.Label(self.fChat)
        self.lChat.place(relx=0.016, rely=0.02, height=21, width=37)
        self.lChat.configure(activebackground="#d9d9d9")
        self.lChat.configure(activeforeground="black")
        self.lChat.configure(anchor='w')
        self.lChat.configure(background="#d9d9d9")
        self.lChat.configure(compound='left')
        self.lChat.configure(disabledforeground="#a3a3a3")
        self.lChat.configure(foreground="black")
        self.lChat.configure(highlightbackground="#d9d9d9")
        self.lChat.configure(highlightcolor="black")
        self.lChat.configure(text='''Chat''')

        self.btnChatEnviarMensagem = tk.Button(self.fChat)
        self.btnChatEnviarMensagem.place(relx=0.571, rely=0.896, height=26
                , width=107)
        self.btnChatEnviarMensagem.configure(activebackground="#d9d9d9")
        self.btnChatEnviarMensagem.configure(activeforeground="black")
        self.btnChatEnviarMensagem.configure(background="#d9d9d9")
        self.btnChatEnviarMensagem.configure(compound='left')
        self.btnChatEnviarMensagem.configure(disabledforeground="#a3a3a3")
        self.btnChatEnviarMensagem.configure(foreground="black")
        self.btnChatEnviarMensagem.configure(highlightbackground="#d9d9d9")
        self.btnChatEnviarMensagem.configure(highlightcolor="black")
        self.btnChatEnviarMensagem.configure(text='''Enviar mensagem''')

        _style_code()
        self.TEntryChat = ttk.Entry(self.fChat)
        self.TEntryChat.place(relx=0.016, rely=0.896, relheight=0.055
                , relwidth=0.499)
        self.TEntryChat.configure(exportselection="0")
        self.TEntryChat.configure(cursor="fleur")

        self.STChat = ScrolledText(self.fChat)
        self.STChat.place(relx=0.016, rely=0.081, relheight=0.784
                , relwidth=0.962)
        self.STChat.configure(background="white")
        self.STChat.configure(exportselection="0")
        self.STChat.configure(font="TkTextFont")
        self.STChat.configure(foreground="black")
        self.STChat.configure(highlightbackground="#d9d9d9")
        self.STChat.configure(highlightcolor="black")
        self.STChat.configure(insertbackground="black")
        self.STChat.configure(insertborderwidth="3")
        self.STChat.configure(selectbackground="#d9d9d9")
        self.STChat.configure(selectforeground="black")
        self.STChat.configure(wrap="none")

        self.FVotacao = tk.Frame(self.top)
        self.FVotacao.place(relx=0.552, rely=0.021, relheight=0.37
                , relwidth=0.434)
        self.FVotacao.configure(relief='groove')
        self.FVotacao.configure(borderwidth="2")
        self.FVotacao.configure(relief="groove")
        self.FVotacao.configure(background="#d9d9d9")
        self.FVotacao.configure(highlightbackground="#d9d9d9")
        self.FVotacao.configure(highlightcolor="black")

        self.Label1 = tk.Label(self.FVotacao)
        self.Label1.place(relx=0.016, rely=0.031, height=23, width=54)
        self.Label1.configure(activebackground="#d9d9d9")
        self.Label1.configure(activeforeground="black")
        self.Label1.configure(anchor='w')
        self.Label1.configure(background="#d9d9d9")
        self.Label1.configure(compound='left')
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(foreground="black")
        self.Label1.configure(highlightbackground="#d9d9d9")
        self.Label1.configure(highlightcolor="black")
        self.Label1.configure(text='''Votação''')

        self.btnVotOpcao2 = ttk.Button(self.FVotacao)
        self.btnVotOpcao2.place(relx=0.016, rely=0.327, height=26, width=347)
        self.btnVotOpcao2.configure(takefocus="")
        self.btnVotOpcao2.configure(text='''Opcao 2''')
        self.btnVotOpcao2.configure(compound='left')

        self.btnVotOpcao3 = ttk.Button(self.FVotacao)
        self.btnVotOpcao3.place(relx=0.016, rely=0.532, height=26, width=347)
        self.btnVotOpcao3.configure(takefocus="")
        self.btnVotOpcao3.configure(text='''Opcao 3''')
        self.btnVotOpcao3.configure(compound='left')

        self.btnVotOpcao1 = ttk.Button(self.FVotacao)
        self.btnVotOpcao1.place(relx=0.016, rely=0.121, height=26, width=347)
        self.btnVotOpcao1.configure(takefocus="")
        self.btnVotOpcao1.configure(text='''Opcao 1''')
        self.btnVotOpcao1.configure(compound='left')

        self.LFStatusVotacao = tk.LabelFrame(self.FVotacao)
        self.LFStatusVotacao.place(relx=0.604, rely=0.028, relheight=0.775
                , relwidth=0.375)
        self.LFStatusVotacao.configure(relief='groove')
        self.LFStatusVotacao.configure(foreground="black")
        self.LFStatusVotacao.configure(text='''Status Votacao''')
        self.LFStatusVotacao.configure(background="#d9d9d9")
        self.LFStatusVotacao.configure(highlightbackground="#d9d9d9")
        self.LFStatusVotacao.configure(highlightcolor="black")

        self.STStatusVotacao = ScrolledText(self.LFStatusVotacao)
        self.STStatusVotacao.place(relx=0.043, rely=0.073, relheight=0.884
                , relwidth=0.93, bordermode='ignore')
        self.STStatusVotacao.configure(background="white")
        self.STStatusVotacao.configure(exportselection="0")
        self.STStatusVotacao.configure(font="TkTextFont")
        self.STStatusVotacao.configure(foreground="black")
        self.STStatusVotacao.configure(highlightbackground="#d9d9d9")
        self.STStatusVotacao.configure(highlightcolor="black")
        self.STStatusVotacao.configure(insertbackground="black")
        self.STStatusVotacao.configure(insertborderwidth="3")
        self.STStatusVotacao.configure(selectbackground="#d9d9d9")
        self.STStatusVotacao.configure(selectforeground="black")
        self.STStatusVotacao.configure(wrap="none")

        self.btnContinuar = ttk.Button(self.FVotacao)
        self.btnContinuar.place(relx=0.44, rely=0.817, height=26, width=77)
        self.btnContinuar.configure(takefocus="")
        self.btnContinuar.configure(text='''Continuar''')
        self.btnContinuar.configure(compound='left')

        self.fHistoria = tk.Frame(self.top)
        self.fHistoria.place(relx=0.014, rely=0.021, relheight=0.951
                , relwidth=0.511)
        self.fHistoria.configure(relief='groove')
        self.fHistoria.configure(borderwidth="2")
        self.fHistoria.configure(relief="groove")
        self.fHistoria.configure(background="#d9d9d9")
        self.fHistoria.configure(highlightbackground="#d9d9d9")
        self.fHistoria.configure(highlightcolor="black")

        self.STHistoria = ScrolledText(self.fHistoria)
        self.STHistoria.place(relx=0.014, rely=0.011, relheight=0.971
                , relwidth=0.963)
        self.STHistoria.configure(background="white")
        self.STHistoria.configure(exportselection="0")
        self.STHistoria.configure(font="TkTextFont")
        self.STHistoria.configure(foreground="black")
        self.STHistoria.configure(highlightbackground="#d9d9d9")
        self.STHistoria.configure(highlightcolor="black")
        self.STHistoria.configure(insertbackground="black")
        self.STHistoria.configure(insertborderwidth="3")
        self.STHistoria.configure(selectbackground="#d9d9d9")
        self.STHistoria.configure(selectforeground="black")
        self.STHistoria.configure(wrap="none")

# The following code is added to facilitate the Scrolled widgets you specified.
class AutoScroll(object):
    '''Configure the scrollbars for a widget.'''
    def __init__(self, master):
        #  Rozen. Added the try-except clauses so that this class
        #  could be used for scrolled entry widget for which vertical
        #  scrolling is not supported. 5/7/14.
        try:
            vsb = ttk.Scrollbar(master, orient='vertical', command=self.yview)
        except:
            pass
        hsb = ttk.Scrollbar(master, orient='horizontal', command=self.xview)
        try:
            self.configure(yscrollcommand=self._autoscroll(vsb))
        except:
            pass
        self.configure(xscrollcommand=self._autoscroll(hsb))
        self.grid(column=0, row=0, sticky='nsew')
        try:
            vsb.grid(column=1, row=0, sticky='ns')
        except:
            pass
        hsb.grid(column=0, row=1, sticky='ew')
        master.grid_columnconfigure(0, weight=1)
        master.grid_rowconfigure(0, weight=1)
        # Copy geometry methods of master  (taken from ScrolledText.py)
        methods = tk.Pack.__dict__.keys() | tk.Grid.__dict__.keys() \
                  | tk.Place.__dict__.keys()
        for meth in methods:
            if meth[0] != '_' and meth not in ('config', 'configure'):
                setattr(self, meth, getattr(master, meth))

    @staticmethod
    def _autoscroll(sbar):
        '''Hide and show scrollbar as needed.'''
        def wrapped(first, last):
            first, last = float(first), float(last)
            if first <= 0 and last >= 1:
                sbar.grid_remove()
            else:
                sbar.grid()
            sbar.set(first, last)
        return wrapped

    def __str__(self):
        return str(self.master)

def _create_container(func):
    '''Creates a ttk Frame with a given master, and use this new frame to
    place the scrollbars and the widget.'''
    def wrapped(cls, master, **kw):
        container = ttk.Frame(master)
        container.bind('<Enter>', lambda e: _bound_to_mousewheel(e, container))
        container.bind('<Leave>', lambda e: _unbound_to_mousewheel(e, container))
        return func(cls, container, **kw)
    return wrapped

class ScrolledText(AutoScroll, tk.Text):
    '''A standard Tkinter Text widget with scrollbars that will
    automatically show/hide as needed.'''
    @_create_container
    def __init__(self, master, **kw):
        tk.Text.__init__(self, master, **kw)
        AutoScroll.__init__(self, master)

import platform
def _bound_to_mousewheel(event, widget):
    child = widget.winfo_children()[0]
    if platform.system() == 'Windows' or platform.system() == 'Darwin':
        child.bind_all('<MouseWheel>', lambda e: _on_mousewheel(e, child))
        child.bind_all('<Shift-MouseWheel>', lambda e: _on_shiftmouse(e, child))
    else:
        child.bind_all('<Button-4>', lambda e: _on_mousewheel(e, child))
        child.bind_all('<Button-5>', lambda e: _on_mousewheel(e, child))
        child.bind_all('<Shift-Button-4>', lambda e: _on_shiftmouse(e, child))
        child.bind_all('<Shift-Button-5>', lambda e: _on_shiftmouse(e, child))

def _unbound_to_mousewheel(event, widget):
    if platform.system() == 'Windows' or platform.system() == 'Darwin':
        widget.unbind_all('<MouseWheel>')
        widget.unbind_all('<Shift-MouseWheel>')
    else:
        widget.unbind_all('<Button-4>')
        widget.unbind_all('<Button-5>')
        widget.unbind_all('<Shift-Button-4>')
        widget.unbind_all('<Shift-Button-5>')

def _on_mousewheel(event, widget):
    if platform.system() == 'Windows':
        widget.yview_scroll(-1*int(event.delta/120),'units')
    elif platform.system() == 'Darwin':
        widget.yview_scroll(-1*int(event.delta),'units')
    else:
        if event.num == 4:
            widget.yview_scroll(-1, 'units')
        elif event.num == 5:
            widget.yview_scroll(1, 'units')

def _on_shiftmouse(event, widget):
    if platform.system() == 'Windows':
        widget.xview_scroll(-1*int(event.delta/120), 'units')
    elif platform.system() == 'Darwin':
        widget.xview_scroll(-1*int(event.delta), 'units')
    else:
        if event.num == 4:
            widget.xview_scroll(-1, 'units')
        elif event.num == 5:
            widget.xview_scroll(1, 'units')
def start_up():
    interface_support.main()

# if __name__ == '__main__':
#     interface_support.main()




