#! /usr/bin/env python3
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 8.1
#  in conjunction with Tcl version 8.6
#    Oct 15, 2025 11:46:44 AM %z  platform: Windows NT

import tkinter as tk

from . import aguardando_jogadores

_debug = True # False to eliminate debug printing from callback functions.

def main(*args):
    '''Main entry point for the application.'''
    global root
    root = tk.Tk()
    root.protocol( 'WM_DELETE_WINDOW' , root.destroy)
    # Creates a toplevel widget.
    global _top1, _w1
    _top1 = root
    _w1 = aguardando_jogadores.Toplevel1(_top1)
    root.mainloop()

# if __name__ == '__main__':
#     aguardando_jogadores.start_up()




