#! /usr/bin/env python3
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 8.1
#  in conjunction with Tcl version 8.6
#    Oct 15, 2025 11:46:39 AM %z  platform: Windows NT

import tkinter as tk
import os.path

_location = os.path.dirname(__file__)

from . import aguardando_jogadores_support

_bgcolor = '#d9d9d9'
_fgcolor = '#000000'
_tabfg1 = 'black' 
_tabfg2 = 'white' 
_bgmode = 'light' 
_tabbg1 = '#d9d9d9' 
_tabbg2 = 'gray40' 

class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''

        top.geometry("600x450+729+175")
        top.minsize(120, 1)
        top.maxsize(1924, 1061)
        top.resizable(1,  1)
        top.title("Toplevel 0")
        top.configure(background="#d9d9d9")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="#000000")

        self.top = top

        self.Frame1 = tk.Frame(self.top)
        self.Frame1.place(relx=0.033, rely=0.044, relheight=0.189
                , relwidth=0.425)
        self.Frame1.configure(relief='groove')
        self.Frame1.configure(borderwidth="2")
        self.Frame1.configure(relief="groove")
        self.Frame1.configure(background="#d9d9d9")
        self.Frame1.configure(highlightbackground="#d9d9d9")
        self.Frame1.configure(highlightcolor="#000000")

        self.LAguardando = tk.Label(self.Frame1)
        self.LAguardando.place(relx=0.235, rely=0.353, height=21, width=134)
        self.LAguardando.configure(activebackground="#d9d9d9")
        self.LAguardando.configure(activeforeground="black")
        self.LAguardando.configure(anchor='w')
        self.LAguardando.configure(background="#d9d9d9")
        self.LAguardando.configure(compound='left')
        self.LAguardando.configure(disabledforeground="#a3a3a3")
        self.LAguardando.configure(foreground="#000000")
        self.LAguardando.configure(highlightbackground="#d9d9d9")
        self.LAguardando.configure(highlightcolor="#000000")
        self.LAguardando.configure(text='''Aguardando Jogadores''')

def start_up():
    aguardando_jogadores_support.main()

if __name__ == '__main__':
    aguardando_jogadores_support.main()




