#! /usr/bin/env python3
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 8.1
#  in conjunction with Tcl version 8.6
#    Oct 15, 2025 11:45:01 AM %z  platform: Windows NT

import sys
import tkinter as tk
import tkinter.ttk as ttk
import os.path

_location = os.path.dirname(__file__)

from . import nome_jogador_support

_bgcolor = '#d9d9d9'
_fgcolor = '#000000'
_tabfg1 = 'black' 
_tabfg2 = 'white' 
_bgmode = 'light' 
_tabbg1 = '#d9d9d9' 
_tabbg2 = 'gray40' 

_style_code_ran = 0
def _style_code():
    global _style_code_ran
    if _style_code_ran: return        
    try: nome_jogador_support.root.tk.call('source',
                                           os.path.join(_location, 'themes', 'default.tcl'))
    except: pass
    style = ttk.Style()
    style.theme_use('default')
    style.configure('.', font = "TkDefaultFont")
    if sys.platform == "win32":
       style.theme_use('winnative')    
    _style_code_ran = 1

class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''

        top.geometry("600x450+729+175")
        top.minsize(120, 1)
        top.maxsize(1924, 1061)
        top.resizable(1,  1)
        top.title("Toplevel 0")
        top.configure(background="#d9d9d9")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="#000000")

        self.top = top

        self.Frame1 = tk.Frame(self.top)
        self.Frame1.place(relx=0.033, rely=0.044, relheight=0.189
                , relwidth=0.425)
        self.Frame1.configure(relief='groove')
        self.Frame1.configure(borderwidth="2")
        self.Frame1.configure(relief="groove")
        self.Frame1.configure(background="#d9d9d9")
        self.Frame1.configure(highlightbackground="#d9d9d9")
        self.Frame1.configure(highlightcolor="#000000")

        _style_code()
        self.TNomeJogador = ttk.Entry(self.Frame1)
        self.TNomeJogador.place(relx=0.039, rely=0.529, relheight=0.224
                , relwidth=0.494)
        self.TNomeJogador.configure(exportselection="0")
        self.TNomeJogador.configure(takefocus="")
        self.TNomeJogador.configure(cursor="ibeam")

        self.TBtnEntrar = ttk.Button(self.Frame1)
        self.TBtnEntrar.place(relx=0.588, rely=0.471, height=26, width=65)
        self.TBtnEntrar.configure(takefocus="")
        self.TBtnEntrar.configure(text='''Entrar''')
        self.TBtnEntrar.configure(compound='left')
        self.TBtnEntrar.configure(cursor="fleur")

        self.TLNomeJogador = ttk.Label(self.Frame1)
        self.TLNomeJogador.place(relx=0.039, rely=0.129, height=26, width=104)
        self.TLNomeJogador.configure(font="TkDefaultFont")
        self.TLNomeJogador.configure(relief="flat")
        self.TLNomeJogador.configure(text='''Nome do jogador''')
        self.TLNomeJogador.configure(compound='left')

def start_up():
    nome_jogador_support.main()

# if __name__ == '__main__':
#     nome_jogador_support.main()




